[workspace]
members = ["programs/*"]
resolver = "2"

[profile.release]
overflow-checks = true

[workspace.package]
version = "0.0.4"
authors = ["Andrew"]
edition = "2021"

#[patch.crates-io]
#solana-decode-error = { version = "=2.1.0", optional = false }