[workspace]
members = ["programs/*", "rust-client", "dynamic-amm-quote"]
resolver = "2"

[profile.release]
overflow-checks = true

[workspace.package]
version = "0.0.4"
authors = ["Andrew"]
edition = "2021"
